/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mysidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'overview'},
      ],
      // "link": {
      //   "type": "generated-index",
      //   "description": "5 minutes to learn the most important Docusaurus concepts."
      // }
    },
    {
      type: 'category',
      label: 'Library',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Jobs',
          collapsed: false,
          items: [
            {type: 'autogenerated', dirName: 'library/jobs'},
          ],
        },
        {
          type: 'category',
          label: 'Reports',
          collapsed: false,
          items: [
            {type: 'autogenerated', dirName: 'library/reports'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Connectors',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Destinations',
          collapsed: false,
          items: [
            {type: 'autogenerated', dirName: 'connectors/destination'},
          ],
        },
        {
          type: 'category',
          label: 'Data sources',
          collapsed: false,
          items: [
            {type: 'autogenerated', dirName: 'connectors/source'},
          ],
        },
      ],
    },

    // 'intro',
    // 'hello',
    // 'overview/why_cashflowy',
    // {type: 'autogenerated', dirName: '.'}
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
