// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // guides: [{ type: 'autogenerated', dirName: 'guides' }],
  // api: [{ type: 'autogenerated', dirName: 'api' }],
  // examples: [{ type: 'autogenerated', dirName: 'examples' }],
  // faq: [{ type: 'autogenerated', dirName: 'faq' }],
  custom:[
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'overview'},
      ],
      // "link": {
      //   "type": "generated-index",
      //   "description": "5 minutes to learn the most important Docusaurus concepts."
      // }
    },
    {
      type: 'category',
      label: 'Library',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Reports',
          collapsed: false,
          items: [
            {type: 'autogenerated', dirName: 'library/reports'},
          ],
        },
        {
          type: 'category',
          label: 'Jobs',
          collapsed: false,
          items: [
            {type: 'autogenerated', dirName: 'library/jobs'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Connectors',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Destinations',
          collapsed: false,
          items: [
            {type: 'autogenerated', dirName: 'connectors/destination'},
          ],
        },
        {
          type: 'category',
          label: 'Data sources',
          collapsed: false,
          items: [
            {type: 'autogenerated', dirName: 'connectors/source'},
          ],
        },
      ],
    },
  ]
}

module.exports = sidebars
